### PR TITLE
Gracefully disconnect on Ctrl+C

### PR DESCRIPTION
**Pull request by Gjum**
Could possibly get extended to other exceptions, e.g. network problems.
Can be a problem when a plugin subscribed to `kill` and does not return
in time.

### CODE REVIEW

**Comment by nickelpro** [comment]
Do we not already do this by catching SIGINT?

**Comment by Gjum** [comment]
I'm on Arch, but my server logged
`lost connection: TranslatableComponent{key='disconnect.genericReason', args=[Internal Exception: java.io.IOException: Error while read(...): Connection reset by peer], <formatting stuff>`
before and
`lost connection: TextComponent{text='Disconnected', <same stuff as above, but no error>`
after, so I think catching SIGINT is not enough?

**Comment by nickelpro** [comment]
So ya, the `'kill'` event is emitted just fine. SpockBot doesn't have any special code to disconnect "gracefully" and I'm not 100% sure what a graceful disconnect looks like. Maybe we should politely shutdown our socket before terminating?

Right now there are no core plugins that hook into `'kill'`, we just die

**Comment by nickelpro** [comment]
A bit of testing later and this seems to be purely a timing thing. Some disconnects get `text='Disconnect'`, others get an error depending on if the server was reading or writing to the players socket at the time. But I can't find any sort of shutdown that doesn't upset the server in at least a handful of cases. Someone should see if the vanilla client can induce the same sort of behavior

**Pull request closed without merging**
