### PR TITLE
Crafting

### PR DESCRIPTION
**Pull request by Gjum**
Yay! It's crafting again! This time using a python 2.7 compatible asynchronous task system, ans also really using minecraft-data now!

TODO:
- [ ] unit tests
- [ ] speed optimization
- [ ] robustness

### CODE REVIEW

**Comment by rom1504** [comment]
Ah ! that's much better than copy-pasting the recipe file in a python file :d

**Comment by nickelpro** [comment]
Is this confirmed not to blow anything up, cause any infinite loops, or otherwise disrupt the peaceful state of SpockLand? If so I'd rather have it in mainline than sitting in PR, will merge in the morning

**Comment by Gjum** [comment]
@nickelpro I discovered some bugs and asynchronous infinite loops, so do not merge it as-is. I probably have some time today to make it ready to merge.

**Comment by Gjum** [comment]
Quick test:
```python
requires = (..., 'craft', ...)

# in an event handler of your choice (e.g. chat):
    self.craft.craft(item_id, metadata, amount)
```

**Comment by nickelpro** [comment]
Works for me, if there are any remaining bugs.... We'll Do It Live!

**Pull request merged**
