### PR TITLE
Player List Implementation

### PR DESCRIPTION
**Pull request by zezadas**
Player List Implementation to keep track of the Players

Do not forget to fix your indentation with tabs instead of spaces

### CODE REVIEW

**Comment by nickelpro** [comment]
This about 500% more code than is necessary and it doesn't implement event emits. But if you want the feature I implemented it in 4f5aeb1f4e238fd09ebde2e5c60b2f39a8cb4801

**Comment by zezadas** [comment]
Sorry if it's more code that it's really necessary. Just trying to help.
If you point me a better direction I will glad to optimize/reduce the code.
thanks

**Comment by nickelpro** [comment]
It's just lack of experience with python idioms that makes your code so verbose. For example instead of:

 `for i in range(len(some_list)):`

Do:

 `for list_element in list:` 

to loop over the list and perform actions on each element. 

It's not that I don't like patches or that I want to discourage you from writing code, please keep doing so (its the best way to improve). I just mean to shoot off a quick message explaining "Why this isn't getting merged immediatly"

**Comment by zezadas** [comment]
No problem, I really liked your project, I'm improving my python...
Also my main goal is to develop a Bot, so I can use it on my Server.
If you interested, please visit my repo ;)
Also if need any help on code, which I can help, please tell.

**Pull request closed without merging**
