### PR TITLE
Fixed 'PLAYER_ENTITY_GAV' constant.

### PR DESCRIPTION
**Pull request by joeListro**
Changed acceleration to be closer to the vanilla MC client settings.

### CODE REVIEW

**Comment by nickelpro** [comment]
What's this based on?

**Comment by joeListro** [comment]
haha oh I'm sorry, I thought Alex had talked to you about this.  We just had to make a change to an open source project and submit a pull request on github for a FOSS class.

**Comment by rom1504** [comment]
0.08 seems to be correct though (http://minecraft.gamepedia.com/Gravity#Motion_of_entities)

**Comment by nickelpro** [comment]
Gravity has all sorts of problems but this constant seems correct, closing

**Pull request closed without merging**
