### PR TITLE
Feature movement teleport

### PR DESCRIPTION
**Pull request by luken**
This is currently stacked on top of #181, I assume #181  should be merged first...

### CODE REVIEW

**Comment by Gjum** [comment]
I do not understand why this has to be part of movement at all. The server can send position updates all the time and we already handle them. And a teleport command interface isn't really needed IMO.

**Comment by Gjum** [comment]
A teleport thing that would fit in spockbot would be the gamemode 3 teleport.

**Comment by luken** [comment]
The time it takes to start the teleport after the command, hit the ground after a teleport is started are both  non-deterministic so adding in idle delays isn't always successful at stalling long enough. 

This interface allows you to tell when a teleport command had completed and the bot was in final position.  This allows for more accurate debugging of pathfinding (it seems to not like it when you start the path calc still in the air).

**Comment by luken** [comment]
Getting old.  Closing.  I've pulled teleport into a 'Commands' custom plugin I am using, if there is interest in having this feature included let me know and I can submit the 'Commands' plugin.

**Pull request closed without merging**
