### PR TITLE
fixed inventory menu opening (minecraft:container)

### PR DESCRIPTION
**Pull request by DefinitlyEvil**

### CODE REVIEW

**Comment by rom1504** [comment]
for reference https://github.com/PrismarineJS/prismarine-windows/blob/master/lib/windows.js#L385 https://github.com/PrismarineJS/mineflayer/pull/293

**Comment by nickelpro** [comment]
Is this something that should be in windows.js?

**Comment by rom1504** [comment]
I think it probably should be in windows.js yes.

**Comment by rom1504** [comment]
Want me to release a new pyhon-minecraft-data version @DefinitlyEvil so you can use it in spockbot ?

**Comment by rom1504** [comment]
done, you can use minecraft-data 0.4.0 in there https://github.com/SpockBotMC/SpockBot/blob/master/setup.py#L18

**Comment by DefinitlyEvil** [comment]
@rom1504 Cool, thanks!

**Pull request closed without merging**
